### ISSUE TITLE
imgur seems to have blocked duckduckgo

### ISSUE THREAD

**Issue by gcobc12632** [azihassan/imgur-duck-proxy#3]
imgur seems to have blocked duckduckgo, and now accessing images through the duckduckgo proxy will result in them being unavailable.

**Comment by azihassan** [comment]
Hi, thanks for the bug report. I confirm that it doesn't work on my setup either. It looks like imgur is having some technical problems at least according to [this tweet](https://twitter.com/imgur/status/1658206795951661057). I hope it's relevant to the issue at hand, I'll update this issue once I have more visiblility.

**Comment by azihassan** [comment]
Looks like it's working today. It could be temporary though since the [status page](https://status.imgur.com/) still mentions ongoing issues. I'll leave this open until the status is back to green

**Comment by azihassan** [comment]
Forgot about this issue. Closing as solved since the [status page](https://status.imgur.com/) has now gone back to green :

![image](https://github.com/azihassan/imgur-duck-proxy/assets/1638227/cae9f5a5-971a-4f46-8097-9f8a36142eec)
